<?php
namespace Nucarf\Merchant\Users\Service;
/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;
use JsonSerializable;
use stdClass;


interface UserServiceIf {
  /**
   * 根据 用户名获取用户信息
   * 
   * 
   * @param string $name
   * @return \Nucarf\Merchant\Users\Entity\User
   */
  public function getUserByName($name);
  /**
   * 商家用户列表
   * 
   * 
   * @param string $keyword
   * @return \Nucarf\Merchant\Users\Entity\UserPaginator
   */
  public function userList($keyword);
  /**
   * 创建一个商家用户
   * 
   * 
   * @param \Nucarf\Merchant\Users\Entity\User $user
   * @return \Nucarf\Merchant\Users\Entity\User
   */
  public function createUser(\Nucarf\Merchant\Users\Entity\User $user);
}


