<?php
namespace Nucarf\Merchant\Users\Service;
/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;
use JsonSerializable;
use stdClass;


class UserService_createUser_args extends TBase implements JsonSerializable {
  static $isValidate = false;

  static $_TSPEC = array(
    1 => array(
      'var' => 'user',
      'isRequired' => false,
      'type' => TType::STRUCT,
      'class' => '\Nucarf\Merchant\Users\Entity\User',
      ),
    );

  /**
   * @var \Nucarf\Merchant\Users\Entity\User
   */
  public $user = null;

  public function __construct($vals=null) {
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'UserService_createUser_args';
  }

  public function read($input)
  {
    return $this->_read('UserService_createUser_args', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('UserService_createUser_args', self::$_TSPEC, $output);
  }

  public function jsonSerialize() {
    $json = new stdClass;
    if ($this->user !== null) {
      $json->user = $this->user;
    }
    return $json;
  }

}

