<?php
namespace Nucarf\Merchant\Users\Entity;

/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;
use JsonSerializable;
use stdClass;


class User extends TBase implements JsonSerializable {
  static $isValidate = false;

  static $_TSPEC = array(
    10 => array(
      'var' => 'id',
      'isRequired' => true,
      'type' => TType::I64,
      ),
    20 => array(
      'var' => 'name',
      'isRequired' => false,
      'type' => TType::STRING,
      ),
    30 => array(
      'var' => 'mobile',
      'isRequired' => false,
      'type' => TType::STRING,
      ),
    40 => array(
      'var' => 'password',
      'isRequired' => false,
      'type' => TType::STRING,
      ),
    );

  /**
   * @var int
   */
  public $id = null;
  /**
   * @var string
   */
  public $name = null;
  /**
   * @var string
   */
  public $mobile = null;
  /**
   * @var string
   */
  public $password = null;

  public function __construct($vals=null) {
    if (is_array($vals)) {
      parent::__construct(self::$_TSPEC, $vals);
    }
  }

  public function getName() {
    return 'User';
  }

  public function read($input)
  {
    return $this->_read('User', self::$_TSPEC, $input);
  }

  public function write($output) {
    return $this->_write('User', self::$_TSPEC, $output);
  }

  public function jsonSerialize() {
    $json = new stdClass;
    if ($this->id !== null) {
      $json->id = (int)$this->id;
    }
    if ($this->name !== null) {
      $json->name = (string)$this->name;
    }
    if ($this->mobile !== null) {
      $json->mobile = (string)$this->mobile;
    }
    if ($this->password !== null) {
      $json->password = (string)$this->password;
    }
    return $json;
  }

}

